### ISSUE TITLE
line.py: using *str keyword args results in broken objects

### ISSUE THREAD

**Issue by BlacklightShining** [awilfox/glorircd#1]
```
>>> line = Line(linestr=':nick!user@host PRIVMSG #test :Hello, world!')
>>> line.tags, line.hostmask, line.command, line.params
(None, None, None, [])
>>> mask = Hostmask(mask='nick!user@host')
>>> mask.nick, mask.user, mask.host
(None, None, None)
```

Presumably this is because of the `self = self.parse(...)` pattern used on lines 20, 55, and 134.

**Comment by awilfox** [comment]
This repo has a very old copy of line.py, with several bugs.  While I would like to start development on glorircd again, I'm not sure when I will be able to.  Until then, you can track further development of line.py at [Elizafox/PyIRC](https://github.com/Elizafox/PyIRC/blob/master/PyIRC/line.py), which is where enhancements, bug fixes, and other niceties for line.py are now pushed.

I may also suggest trying out PyIRC itself for any Python IRC development needs.  We have [great docs](http://foxkit.us/PyIRC) and [some examples](https://github.com/Elizafox/PyIRC/tree/master/examples) to get you started.  Happy coding!
